### ISSUE TITLE
It doesn't work with HEIF or JPEG

### ISSUE THREAD

**Issue by Sherlozk** [DigiDNA/ISOBMFF-Explorer#1]
![image](https://user-images.githubusercontent.com/7531339/33748756-4fadb028-dc05-11e7-9b07-1a7d1b12c08f.png)

**Comment by macmade** [comment]
Would be nice to have a little more details than just “it doesn’t work”.
Please provide the file you are trying to open.

**Comment by macmade** [comment]
No feedback - Closing...
